"""In-memory placeholder dataset.

Used until the trained model + Postgres are wired in. Every field matches
the frontend contract so the UI can be built against real-looking data.
"""
from typing import Dict, List

_CUSTOMERS: List[dict] = [
    {
        "customer_id": "cus_001",
        "name": "Northwind Traders",
        "subscription_plan": "Enterprise",
        "health_score": 41.2,
        "churn_probability": 0.72,
        "risk_tier": "high",
        "monthly_usage_pct": 34.0,
        "recommended_action": "Schedule an executive business review; usage dropped 40% MoM.",
        "shap_reasons": [
            {"feature": "login_frequency", "contribution": 0.28},
            {"feature": "support_ticket_count", "contribution": 0.19},
            {"feature": "feature_usage", "contribution": 0.14},
            {"feature": "feedback_score", "contribution": -0.05},
        ],
    },
    {
        "customer_id": "cus_002",
        "name": "Acme Robotics",
        "subscription_plan": "Growth",
        "health_score": 68.5,
        "churn_probability": 0.34,
        "risk_tier": "medium",
        "monthly_usage_pct": 61.0,
        "recommended_action": "Nudge toward the analytics module — low feature adoption for their plan.",
        "shap_reasons": [
            {"feature": "feature_usage", "contribution": 0.17},
            {"feature": "monthly_usage_pct", "contribution": -0.11},
            {"feature": "payment_status", "contribution": 0.08},
            {"feature": "feedback_score", "contribution": -0.09},
        ],
    },
    {
        "customer_id": "cus_003",
        "name": "Blue Harbor Health",
        "subscription_plan": "Enterprise",
        "health_score": 88.9,
        "churn_probability": 0.08,
        "risk_tier": "low",
        "monthly_usage_pct": 92.0,
        "recommended_action": "Healthy account — flag as expansion / upsell candidate.",
        "shap_reasons": [
            {"feature": "monthly_usage_pct", "contribution": -0.31},
            {"feature": "login_frequency", "contribution": -0.22},
            {"feature": "feedback_score", "contribution": -0.18},
            {"feature": "support_ticket_count", "contribution": 0.04},
        ],
    },
    {
        "customer_id": "cus_004",
        "name": "Cedar & Co.",
        "subscription_plan": "Starter",
        "health_score": 52.3,
        "churn_probability": 0.55,
        "risk_tier": "high",
        "monthly_usage_pct": 45.0,
        "recommended_action": "Payment failed twice this cycle — trigger billing recovery flow.",
        "shap_reasons": [
            {"feature": "payment_status", "contribution": 0.33},
            {"feature": "monthly_usage_pct", "contribution": 0.09},
            {"feature": "feature_usage", "contribution": 0.06},
            {"feature": "login_frequency", "contribution": -0.03},
        ],
    },
    {
        "customer_id": "cus_005",
        "name": "Summit Analytics",
        "subscription_plan": "Growth",
        "health_score": 74.1,
        "churn_probability": 0.21,
        "risk_tier": "medium",
        "monthly_usage_pct": 70.0,
        "recommended_action": "Send onboarding follow-up for the two seats added last week.",
        "shap_reasons": [
            {"feature": "feature_usage", "contribution": -0.12},
            {"feature": "login_frequency", "contribution": -0.14},
            {"feature": "support_ticket_count", "contribution": 0.07},
            {"feature": "feedback_score", "contribution": -0.06},
        ],
    },
    {
        "customer_id": "cus_006",
        "name": "London Financial",
        "subscription_plan": "Enterprise",
        "health_score": 91.5,
        "churn_probability": 0.05,
        "risk_tier": "low",
        "monthly_usage_pct": 88.0,
        "recommended_action": "Strong account. Nudge towards enterprise add-on package.",
        "shap_reasons": [
            {"feature": "monthly_usage_pct", "contribution": -0.28},
            {"feature": "login_frequency", "contribution": -0.19},
            {"feature": "support_ticket_count", "contribution": 0.02},
        ],
    },
    {
        "customer_id": "cus_007",
        "name": "Paris Logistics",
        "subscription_plan": "Growth",
        "health_score": 58.2,
        "churn_probability": 0.42,
        "risk_tier": "medium",
        "monthly_usage_pct": 50.0,
        "recommended_action": "Onboarding review requested. Low activity in core logistics logs.",
        "shap_reasons": [
            {"feature": "feature_usage", "contribution": 0.12},
            {"feature": "login_frequency", "contribution": 0.18},
            {"feature": "feedback_score", "contribution": -0.04},
        ],
    },
    {
        "customer_id": "cus_008",
        "name": "Singapore Tech",
        "subscription_plan": "Enterprise",
        "health_score": 35.8,
        "churn_probability": 0.78,
        "risk_tier": "high",
        "monthly_usage_pct": 22.0,
        "recommended_action": "High churn risk! Usage dropped 60%. Schedule emergency check-in.",
        "shap_reasons": [
            {"feature": "login_frequency", "contribution": 0.35},
            {"feature": "support_ticket_count", "contribution": 0.22},
            {"feature": "payment_status", "contribution": 0.10},
        ],
    },
    {
        "customer_id": "cus_009",
        "name": "São Paulo Retail",
        "subscription_plan": "Starter",
        "health_score": 79.4,
        "churn_probability": 0.18,
        "risk_tier": "medium",
        "monthly_usage_pct": 72.0,
        "recommended_action": "Billing is healthy. Proactive feature optimization package sent.",
        "shap_reasons": [
            {"feature": "feedback_score", "contribution": -0.14},
            {"feature": "monthly_usage_pct", "contribution": -0.09},
            {"feature": "support_ticket_count", "contribution": 0.05},
        ],
    },
    {
        "customer_id": "cus_010",
        "name": "Toronto Devs",
        "subscription_plan": "Growth",
        "health_score": 85.1,
        "churn_probability": 0.09,
        "risk_tier": "low",
        "monthly_usage_pct": 90.0,
        "recommended_action": "Highly engaged account. Good candidate for referral program.",
        "shap_reasons": [
            {"feature": "login_frequency", "contribution": -0.26},
            {"feature": "feature_usage", "contribution": -0.15},
            {"feature": "feedback_score", "contribution": -0.08},
        ],
    },
    {
        "customer_id": "cus_011",
        "name": "Anchorage Shipping",
        "subscription_plan": "Growth",
        "health_score": 64.0,
        "churn_probability": 0.38,
        "risk_tier": "medium",
        "monthly_usage_pct": 58.0,
        "recommended_action": "API usage velocity dropping. Recommend sending tutorials.",
        "shap_reasons": [
            {"feature": "login_frequency", "contribution": 0.15},
            {"feature": "feature_usage", "contribution": 0.08},
        ],
    },
    {
        "customer_id": "cus_012",
        "name": "Lagos Ventures",
        "subscription_plan": "Enterprise",
        "health_score": 94.0,
        "churn_probability": 0.04,
        "risk_tier": "low",
        "monthly_usage_pct": 96.0,
        "recommended_action": "Perfect health. Flag for case study request.",
        "shap_reasons": [
            {"feature": "login_frequency", "contribution": -0.32},
            {"feature": "feedback_score", "contribution": -0.25},
        ],
    },
    {
        "customer_id": "cus_013",
        "name": "Auckland Media",
        "subscription_plan": "Pro",
        "health_score": 48.0,
        "churn_probability": 0.52,
        "risk_tier": "high",
        "monthly_usage_pct": 39.0,
        "recommended_action": "High support ticket count. Priority response required.",
        "shap_reasons": [
            {"feature": "support_ticket_count", "contribution": 0.24},
            {"feature": "feature_usage", "contribution": 0.10},
        ],
    },
    {
        "customer_id": "cus_014",
        "name": "Reykjavík Fisheries",
        "subscription_plan": "Starter",
        "health_score": 72.0,
        "churn_probability": 0.15,
        "risk_tier": "low",
        "monthly_usage_pct": 78.0,
        "recommended_action": "Steady account. Billing and invoices in good standing.",
        "shap_reasons": [
            {"feature": "feedback_score", "contribution": -0.11},
            {"feature": "monthly_usage_pct", "contribution": -0.06},
        ],
    },
    {
        "customer_id": "cus_015",
        "name": "Lima Agricultures",
        "subscription_plan": "Growth",
        "health_score": 38.5,
        "churn_probability": 0.74,
        "risk_tier": "high",
        "monthly_usage_pct": 31.0,
        "recommended_action": "Involuntary billing failures. Manual card update check required.",
        "shap_reasons": [
            {"feature": "payment_status", "contribution": 0.38},
            {"feature": "login_frequency", "contribution": 0.14},
        ],
    },
    {
        "customer_id": "cus_016",
        "name": "Honolulu Resorts",
        "subscription_plan": "Enterprise",
        "health_score": 87.0,
        "churn_probability": 0.07,
        "risk_tier": "low",
        "monthly_usage_pct": 91.0,
        "recommended_action": "Strong usage trend. Reach out to schedule expansion sync.",
        "shap_reasons": [
            {"feature": "monthly_usage_pct", "contribution": -0.22},
            {"feature": "feedback_score", "contribution": -0.16},
        ],
    },
    {
        "customer_id": "cus_017",
        "name": "Dubai Hospitality",
        "subscription_plan": "Growth",
        "health_score": 62.0,
        "churn_probability": 0.28,
        "risk_tier": "medium",
        "monthly_usage_pct": 65.0,
        "recommended_action": "Good login rate. Nudge to add new developer seats.",
        "shap_reasons": [
            {"feature": "login_frequency", "contribution": -0.14},
            {"feature": "support_ticket_count", "contribution": 0.08},
        ],
    },
    {
        "customer_id": "cus_018",
        "name": "Casablanca Textile",
        "subscription_plan": "Starter",
        "health_score": 55.0,
        "churn_probability": 0.44,
        "risk_tier": "medium",
        "monthly_usage_pct": 48.0,
        "recommended_action": "Decaying telemetry frequency. Send automatic engagement newsletter.",
        "shap_reasons": [
            {"feature": "login_frequency", "contribution": 0.12},
            {"feature": "feature_usage", "contribution": 0.09},
        ],
    },
    {
        "customer_id": "cus_019",
        "name": "Seoul Semiconductors",
        "subscription_plan": "Enterprise",
        "health_score": 89.5,
        "churn_probability": 0.06,
        "risk_tier": "low",
        "monthly_usage_pct": 94.0,
        "recommended_action": "Optimal performance. Prepare Q3 expansion contract.",
        "shap_reasons": [
            {"feature": "feature_usage", "contribution": -0.24},
            {"feature": "monthly_usage_pct", "contribution": -0.18},
        ],
    },
    {
        "customer_id": "cus_020",
        "name": "Vancouver Analytics",
        "subscription_plan": "Pro",
        "health_score": 40.8,
        "churn_probability": 0.68,
        "risk_tier": "high",
        "monthly_usage_pct": 32.0,
        "recommended_action": "Friction during batch pipelines. Assign technical CSM.",
        "shap_reasons": [
            {"feature": "support_ticket_count", "contribution": 0.26},
            {"feature": "feature_usage", "contribution": 0.12},
        ],
    },
]

_BY_ID: Dict[str, dict] = {c["customer_id"]: c for c in _CUSTOMERS}


def list_customers() -> List[dict]:
    return _CUSTOMERS


def get_customer(customer_id: str) -> dict | None:
    return _BY_ID.get(customer_id)
